let category='cooker',series='all',favOnly=false,compareItems=[];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};let favorites=store.get('boschFav',[]);
function key(c,n){return c+'|'+n}function norm(s){return String(s||'').toLowerCase().replace(/\s/g,'')} function notify(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}
function modelText(n,m){return n+' '+(m.series||'')+' '+(m.subtype||'')+' '+(m.features||[]).join(' ')}
function buildFilters(){let ss=[...new Set(Object.values(data[category]||{}).map(m=>m.series).filter(Boolean))].sort((a,b)=>b-a);filters.innerHTML=['all',...ss].map(x=>`<button class="chip ${series===x?'active':''}" onclick="setSeries('${x}')">${x==='all'?'كل السلاسل':'Series '+x}</button>`).join('')}
function setSeries(s){series=s==='all'?'all':Number(s);buildFilters();renderList()} function toggleFavFilter(){favOnly=!favOnly;favFilter.classList.toggle('active',favOnly);renderList()} function clearSearch(){search.value='';renderList()}
function renderList(){const q=norm(search.value);let e=[];if(q)Object.entries(data).forEach(([c,ms])=>Object.entries(ms).forEach(([n,m])=>{if(norm(modelText(n,m)).includes(q))e.push([c,n,m])}));else e=Object.entries(data[category]||{}).map(([n,m])=>[category,n,m]).filter(([c,n,m])=>(series==='all'||m.series===series)&&(!favOnly||favorites.includes(key(c,n))));clear.style.display=q?'block':'none';count.textContent=e.length;list.innerHTML=e.length?e.map(([c,n,m])=>row(c,n,m)).join(''):'<div class="empty">لا توجد نتائج.</div>'}
function row(c,n,m){return `<div class="product" onclick="openDetail('${c}','${n}')"><div><div class="over">${labels[c]}</div><div class="model">${n}</div><div class="desc">${m.subtype||''}${m.series?' · Series '+m.series:''}</div></div><button class="star ${favorites.includes(key(c,n))?'on':''}" onclick="event.stopPropagation();toggleFav('${c}','${n}')">★</button></div>`}
function toggleFav(c,n){const k=key(c,n),i=favorites.indexOf(k);i<0?favorites.push(k):favorites.splice(i,1);store.set('boschFav',favorites);renderList();notify(i<0?'تمت الإضافة للمفضلة':'تمت الإزالة')}
function openDetail(c,n){const m=data[c][n];catalog.style.display='none';detail.innerHTML=`<button class="back" onclick="backHome()">→ رجوع</button><div class="card product-hero"><div class="eyebrow">${labels[c]} ${m.series?'· SERIES '+m.series:''}</div><div class="hero-model">${n}</div><div class="value">${m.subtype||labels[c]} Bosch ${n}. اختر الموديل حسب احتياج العميل والمساحة المتاحة.</div><div class="badges">${(m.features||[]).map(x=>`<span class="badge">${x}</span>`).join('')}</div></div><div class="panel"><div class="title">أهم نقاط البيع</div>${(m.features||[]).map((x,i)=>`<div class="benefit"><div class="num">${i+1}</div><div><b>${x}</b><p>ميزة تساعد على تحسين تجربة الاستخدام حسب احتياج العميل.</p></div></div>`).join('')}</div><div class="panel"><div class="title">Sales Talk</div><div class="talk">Bosch ${n}: ${(m.features||[]).slice(0,3).join('، ')}.</div></div>`;detail.classList.add('open');scrollTo(0,0)}
function backHome(){detail.classList.remove('open');catalog.style.display='block';renderList();scrollTo(0,0)}
function setCategory(c){category=c;series='all';favOnly=false;document.querySelectorAll('.cats button').forEach(b=>b.classList.toggle('active',b.dataset.cat===c));buildFilters();renderList()}
