/* Bosch Trainer AI - Local Product Image Manager */
(function(){
'use strict';
const DB='boschTrainerImages', STORE='images';
let db=null, current={c:null,n:null};
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function getImage(k){return new Promise(res=>{if(!db)return res(null);const r=db.transaction(STORE).objectStore(STORE).get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>res(null)})}
function putImage(k,v){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(v,k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function delImage(k){return new Promise(res=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(k);r.onsuccess=()=>res();r.onerror=()=>res()})}
function k(c,n){return c+'|'+n}
function folder(c){return ({cooker:'cookers',dw:'dishwashers',fridge:'fridges',laundry:'laundry',homecare:'homecare',beverage:'beverages',foodprep:'food-preparation',builtin:'built-in'})[c]||'products'}
function official(c,n){return `images/${folder(c)}/${n}.webp`}
function placeholder(c,n){const icon=c==='fridge'?'❄':c==='dw'?'◫':'♨';return `<div class="img-empty"><div class="img-empty-icon">${icon}</div><b>لا توجد صورة مؤكدة</b><small>${n}</small></div>`}
async function srcFor(c,n){const local=await getImage(k(c,n));return local||official(c,n)}
function styles(){const x=document.createElement('style');x.textContent=`.product{grid-template-columns:76px 1fr auto!important;gap:10px}.product-image-box{width:76px;height:76px;background:#f7f9fa;border:1px solid #d5dade;border-radius:7px;display:grid;place-items:center;overflow:hidden}.product-image-box img{width:100%;height:100%;object-fit:contain}.mini-empty{font-size:9px;color:#687078;text-align:center;padding:5px}.image-manager{background:#fff;border:1px solid #d5dade;box-shadow:0 7px 24px #001e3515;padding:12px;margin-bottom:10px}.image-stage{height:260px;background:#f7f9fa;border:1px dashed #aeb6bb;display:grid;place-items:center;overflow:hidden}.image-stage img{width:100%;height:100%;object-fit:contain}.img-empty{text-align:center;color:#687078}.img-empty-icon{font-size:42px;color:#005691}.img-empty b,.img-empty small{display:block;margin-top:5px}.image-buttons{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.image-buttons button{padding:11px;border:1px solid #005691;font-weight:700;background:#fff;color:#005691}.image-buttons .save{background:#005691;color:#fff}.image-buttons .danger{border-color:#e20015;color:#e20015}.image-help{font-size:10px;color:#687078;line-height:1.6;margin-top:8px}.img-modal{position:fixed;inset:0;background:#000b;z-index:999999;display:none;place-items:center;padding:15px}.img-modal.open{display:grid}.img-modal-box{background:#fff;width:min(100%,480px);padding:14px}.img-modal img{width:100%;max-height:70vh;object-fit:contain}.img-modal button{width:100%;padding:12px;margin-top:8px}.global-image-input{display:none}`;document.head.appendChild(x)}
const oldRow=window.row;
window.row=function(c,n,m){let html=oldRow(c,n,m);html=html.replace('<div><div class="over">',`<div class="product-image-box" data-img-key="${k(c,n)}" data-c="${c}" data-n="${n}"><div class="mini-empty">إضافة صورة</div></div><div><div class="over">`);setTimeout(()=>hydrateCards(),0);return html}
async function hydrateCards(){for(const box of document.querySelectorAll('.product-image-box:not([data-ready])')){box.dataset.ready='1';const c=box.dataset.c,n=box.dataset.n,local=await getImage(k(c,n));const img=document.createElement('img');img.alt='Bosch '+n;img.loading='lazy';img.src=local||official(c,n);img.onerror=()=>{box.innerHTML='<div class="mini-empty">اضغط على الموديل<br>لإضافة صورة</div>'};img.onload=()=>{box.innerHTML='';box.appendChild(img)};}}
const oldOpen=window.openDetail;
window.openDetail=function(c,n){current={c,n};oldOpen(c,n);setTimeout(()=>injectManager(c,n),0)}
async function injectManager(c,n){const detail=document.getElementById('detail');if(!detail||detail.querySelector('.image-manager'))return;const manager=document.createElement('div');manager.className='image-manager';manager.innerHTML=`<div class="image-stage" id="imageStage">${placeholder(c,n)}</div><input class="global-image-input" id="productImageInput" type="file" accept="image/*"><div class="image-buttons"><button class="save" id="chooseImage">+ إضافة / تغيير الصورة</button><button id="downloadImage">تجهيز WebP لـ GitHub</button><button id="viewImage">عرض بالحجم الكامل</button><button class="danger" id="deleteImage">حذف الصورة المحفوظة</button></div><div class="image-help">الحفظ المحلي يظهر على هذا الجهاز فقط. زر WebP ينزّل صورة باسم <b>${n}.webp</b> لرفعها داخل <b>images/${folder(c)}/</b> حتى تظهر لجميع المستخدمين.</div>`;const back=detail.querySelector('.back');back.after(manager);const input=manager.querySelector('#productImageInput');manager.querySelector('#chooseImage').onclick=()=>input.click();input.onchange=e=>processFile(e.target.files[0],c,n);manager.querySelector('#deleteImage').onclick=()=>removeCurrent(c,n);manager.querySelector('#downloadImage').onclick=()=>downloadCurrent(c,n);manager.querySelector('#viewImage').onclick=()=>viewCurrent(c,n);await showStage(c,n)}
async function processFile(file,c,n){if(!file)return;if(!file.type.startsWith('image/'))return notify('اختر ملف صورة');if(file.size>15*1024*1024)return notify('حجم الصورة أكبر من 15MB');const url=URL.createObjectURL(file),img=new Image();img.onload=async()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),cv=document.createElement('canvas');cv.width=w;cv.height=h;const ctx=cv.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);const data=cv.toDataURL('image/webp',.86);URL.revokeObjectURL(url);try{await putImage(k(c,n),data);await showStage(c,n);renderList();notify('تم حفظ الصورة على هذا الجهاز')}catch(e){notify('مساحة التخزين غير كافية')}};img.onerror=()=>notify('تعذر قراءة الصورة');img.src=url}
async function showStage(c,n){const stage=document.getElementById('imageStage');if(!stage)return;const local=await getImage(k(c,n));const img=document.createElement('img');img.alt='Bosch '+n;img.src=local||official(c,n);img.onload=()=>{stage.innerHTML='';stage.appendChild(img)};img.onerror=()=>stage.innerHTML=placeholder(c,n)}
async function removeCurrent(c,n){await delImage(k(c,n));await showStage(c,n);renderList();notify('تم حذف الصورة المحفوظة')}
async function getDrawable(c,n){const local=await getImage(k(c,n));return local||official(c,n)}
async function downloadCurrent(c,n){const src=await getDrawable(c,n),img=new Image();img.crossOrigin='anonymous';img.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(img.width,img.height)),cv=document.createElement('canvas');cv.width=Math.round(img.width*scale);cv.height=Math.round(img.height*scale);const ctx=cv.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cv.width,cv.height);ctx.drawImage(img,0,0,cv.width,cv.height);cv.toBlob(blob=>{if(!blob)return notify('تعذر تجهيز الصورة');const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=n+'.webp';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('تم تنزيل '+n+'.webp')},'image/webp',.88)};img.onerror=()=>notify('أضف صورة أولًا');img.src=src}
async function viewCurrent(c,n){const src=await getDrawable(c,n),modal=document.getElementById('imgModal'),img=modal.querySelector('img');img.onerror=()=>notify('لا توجد صورة للعرض');img.src=src;modal.classList.add('open')}
function modal(){const m=document.createElement('div');m.id='imgModal';m.className='img-modal';m.innerHTML='<div class="img-modal-box"><img alt="صورة المنتج"><button>إغلاق</button></div>';m.querySelector('button').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};document.body.appendChild(m)}
async function start(){styles();modal();try{await openDB()}catch(e){notify('تعذر تشغيل حفظ الصور على هذا الجهاز')}renderList()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start();
})();
